export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST'
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS'
export const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE'

export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE'
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS'
export const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE'

export const GET_RECIPE_REQUEST = 'GET_RECIPE_REQUEST'
export const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS'
export const GET_RECIPE_FAILURE = 'GET_RECIPE_FAILURE'

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const CHANGE_FORM_PRODUCT_NAME = 'CHANGE_FORM_PRODUCT_NAME'
export const CHANGE_FORM_PRODUCT_CATEGORY = 'CHANGE_FORM_PRODUCT_CATEGORY'

export const ADD_CATEGORY_PRODUCT_REQUEST = 'ADD_CATEGORY_PRODUCT_REQUEST'
export const ADD_CATEGORY_PRODUCT_SUCCESS = 'ADD_CATEGORY_PRODUCT_SUCCESS'
export const ADD_CATEGORY_PRODUCT_FAILURE = 'ADD_CATEGORY_PRODUCT_FAILURE'
export const CHANGE_NAME_FORM_CATEGORY = 'CHANGE_NAME_CATEGORY'
export const GET_ALL_CATEGORY_PRODUCT = 'GET_ALL_CATEGORY_PRODUCT'

export const DELETE_CATEGORY_PRODUCT_REQUEST = 'DELETE_CATEGORY_PRODUCT'
export const DELETE_CATEGORY_PRODUCT_SUCCESS = 'DELETE_CATEGORY_PRODUCT_SUCCESS'
export const DELETE_CATEGORY_PRODUCT_FAILURE = 'DELETE_CATEGORY_PRODUCT_FAILURE'

export const NAVIGATE_TO = 'NAVIGATE_TO'
export const NAVIGATE_BACK = 'NAVIGATE_BACK'
