export const ADD_CATEGORY_PRODUCT_REQUEST = 'ADD_CATEGORY_PRODUCT_REQUEST'
export const ADD_CATEGORY_PRODUCT_SUCCESS = 'ADD_CATEGORY_PRODUCT_SUCCESS'
export const ADD_CATEGORY_PRODUCT_FAILURE = 'ADD_CATEGORY_PRODUCT_FAILURE'
export const CHANGE_NAME_FORM_CATEGORY = 'CHANGE_NAME_CATEGORY'
export const GET_ALL_CATEGORY_PRODUCT = 'GET_ALL_CATEGORY_PRODUCT'

export const DELETE_CATEGORY_PRODUCT_REQUEST = 'DELETE_CATEGORY_PRODUCT'
export const DELETE_CATEGORY_PRODUCT_SUCCESS = 'DELETE_CATEGORY_PRODUCT_SUCCESS'
export const DELETE_CATEGORY_PRODUCT_FAILURE = 'DELETE_CATEGORY_PRODUCT_FAILURE'
