export const ADD_RECIPE_REQUEST = "ADD_RECIPE_REQUEST";
export const ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS";
export const ADD_RECIPE_FAILURE = "ADD_RECIPE_FAILURE";

export const DELETE_RECIPE_REQUEST = "DELETE_RECIPE";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_FAILURE = "DELETE_RECIPE_FAILURE";

export const GET_RECIPE_REQUEST = "GET_RECIPE_REQUEST";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_FAILURE = "GET_RECIPE_FAILURE";

export const GET_ALL_RECIPES_REQUEST = "GET_ALL_RECIPES_REQUEST";
export const GET_ALL_RECIPES_SUCCESS = "GET_ALL_RECIPES_SUCCESS";
export const GET_ALL_RECIPES_FAILURE = "GET_ALL_RECIPES_FAILURE";

export const CHANGE_RECIPE_NAME = "CHANGE_RECIPE_NAME";
export const ADD_RECIPE_STEP = "ADD_RECIPE_STEP";
export const CHANGE_RECIPE_STEP = "CHANGE_RECIPE_STEP";
export const ADD_RECIPE_PRODUCT = "ADD_RECIPE_PRODUCT";
export const CHANGE_RECIPE_PRODUCT = "CHANGE_RECIPE_PRODUCT";
export const CHANGE_RECIPE_PRODUCT_UNIT = "CHANGE_RECIPE_PRODUCT_UNIT";
export const CHANGE_RECIPE_PRODUCT_QUANTITY = "CHANGE_RECIPE_PRODUCT_QUANTITY";
